INSERT INTO `reminiscensdb`.`Public_Memento`
(
`migration_id`,
`headline`,
`text`,
`type`,
`resource_type`,
`category`,
`source`,
`source_url`,
`resource_url`,
`resource_thumbnail_url`,
`author`,
`collection`,
`collection_type`,
`is_collection`,
`nationality`,
`locale`,
`haschcode`,
`file_hashcode`,
`file_name`,
`contributor_type`,
`contributor`,
`creation_date`,
`last_update`,
`fuzzy_startdate`,
`location_start_id`,
`fuzzy_enddate`,
`location_end_id`,
`indexed`,
`tags`)

SELECT
`Famous_Person`.`famous_id`,
`Famous_Person`.`fullname`,
`Famous_Person`.`famous_for`,
'Personaggio Storico',
`Famous_Person`.`resource_type`,
`Famous_Person`.`category`,
`Famous_Person`.`source`,
`Famous_Person`.`source_url`,
`Famous_Person`.`picture_url`,
NULL,
NULL,
NULL,
NULL,
0,
(select italian_name from Country where `Country`.`country_id` = `Famous_Person`.`nationality_country_id`) as `nationality`,
`Famous_Person`.`locale`,
NULL,
NULL,
NULL,
'SYSTEM',
NULL,
`Famous_Person`.`creation_date`,
`Famous_Person`.`last_update`,
`Famous_Person`.`birthdate_fuzzy_id`,
`Famous_Person`.`birthplace_id`,
`Famous_Person`.`deathdate_fuzzy_id`,
`Famous_Person`.`deathplace_id`,
`Famous_Person`.`indexed`,
`Famous_Person`.`tags`
FROM `reminiscensdb`.`Famous_Person`;

