INSERT INTO `reminiscensdb`.`Public_Memento`
(
`migration_id`,
`headline`,
`text`,
`type`,
`resource_type`,
`category`,
`source`,
`source_url`,
`resource_url`,
`resource_thumbnail_url`,
`author`,
`collection`,
`collection_type`,
`is_collection`,
`nationality`,
`locale`,
`haschcode`,
`file_hashcode`,
`file_name`,
`contributor_type`,
`contributor`,
`creation_date`,
`last_update`,
`fuzzy_startdate`,
`location_start_id`,
`fuzzy_enddate`,
`location_end_id`,
`indexed`,
`tags`)

SELECT
`Contributed_Memento`.`contributed_memento_id`,
`Contributed_Memento`.`headline`,
`Contributed_Memento`.`text`,
`Contributed_Memento`.`type`,
`Contributed_Memento`.`resource_type`,
`Contributed_Memento`.`category`,
`Contributed_Memento`.`source`,
`Contributed_Memento`.`source_url`,
`Contributed_Memento`.`resource_url`,
`Contributed_Memento`.`resource_thumbnail_url`,
`Contributed_Memento`.`author`,
`Contributed_Memento`.`collection`,
NULL,
0,
`Contributed_Memento`.`nationality`,
`Contributed_Memento`.`locale`,
`Contributed_Memento`.`haschcode`,
`Contributed_Memento`.`file_hashcode`,
NULL,
`Contributed_Memento`.`added_by`,
NULL,
"2013-08-27 12:00:00",
"2013-08-27 12:00:00",
`Contributed_Memento`.`fuzzy_startdate`,
`Contributed_Memento`.`location_start_id`,
`Contributed_Memento`.`fuzzy_enddate`,
`Contributed_Memento`.`location_end_id`,
0,
NULL
FROM `reminiscensdb`.`Contributed_Memento`;

